#!/usr/bin/env bash

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config external_bar 		    all:30:0

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

setup_space() {
    local idx="$1"
    local name="$2"
    local display="$3"
    local space=
    echo "setup space $idx : $name"

    space=$(yabai -m query --spaces --space "$idx")
    if [ -z "$space" ]; then
        yabai -m space "$idx" --create
    fi

    yabai -m space "$idx" --display "$display" --label "$name"
}

setup_space 1 Firefox 1
setup_space 2 Chrome 1
setup_space 3 Slack 1
setup_space 4 Quip 1
setup_space 5 Spare1 1

setup_space 6 Docker 2
setup_space 7 Kitty 2
setup_space 8 Spare2 2
setup_space 9 Idea 2
setup_space 10 Rider 2

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 10)'); do
  yabai -m space --destroy 7
done

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add app="AnyConnect" manage=off
yabai -m rule --add app="KeePassXC" manage=off
yabai -m rule --add app="choose" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="HHKB" app="HHKB Keymap Tool" title="About This Mac" manage=off

yabai -m rule --add app="Slack" space="Slack"
yabai -m rule --add app="Google Chrome" space="Chrome"
yabai -m rule --add app="Firefox" space="Firefox"

yabai -m rule --add app="Docker Desktop" space="Docker"
yabai -m rule --add app="kitty" space="Kitty"
yabai -m rule --add app="JetBrains Rider" space="Rider"
yabai -m rule --add app="Huddle with" manage=off
yabai -m rule --add app="Obsidian" display=1 sticky="on" grid=1:3:3:1:1:1

## Super Jetbrains mode
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA|Rider)$'
yabai -m rule --add app="${JB_Apps}" manage=off
# If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
# yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on 
yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on

echo "yabai configuration loaded.."
