[".config/zsh/.antidote"]
    type = "git-repo"
    clone = {args = ["--depth=1"]}
    url = "https://github.com/mattmc3/antidote.git"

[".config/zsh/fzf-git"]
    type = "git-repo"
    clone = {args = ["--depth=1"]}
    url = "https://github.com/junegunn/fzf-git.sh.git"
