#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
file=$(mktemp)
cat - > $file
for f in $SCRIPT_DIR/final_filter.d/*; do
    [ -e "$f" ] || continue
    cat $file | $f | sponge $file
done
cat $file
