[window.padding]
x = 3
y = 3

[font]
normal = { family = "MesloLGM Nerd Font Mono" }
size = 12

[colors.primary]
foreground = "#979eab"
background = "#282c34"

[colors.cursor]
cursor = "#cccccc"

[colors.selection]
text = "#282c34"
background = "#979eab"

[colors.normal]
black = "#282c34"
red = "#e06c75"
green ="#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#be5046"
cyan = "#56b6c2"
white = "#979eab"
    
[colors.bright]
black = "#393e48"
red = "#d19a66"
green = "#56b6c2"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#be5046"
cyan = "#56b6c2"
white = "#abb2bf"
